"""The robot contract: what a skill needs from whatever executes it.

Skills, practice, replay and the dashboard talk to a *back-end*. Two exist:

- `sim` (`World`): MuJoCo is the robot. It knows everything (object ground truth, contacts).
- `real` (`RealBackend`, below): servos move a real arm. The same MuJoCo model runs next to it as a *twin*: it
  gives geometry and inverse kinematics, imagines moves before they are made, and shadows the real arm.

What a skill may rely on, and what a real arm must therefore provide:

  Command    step(action)           one control tick (20 Hz): action = (vx, vy, vz, grip, yaw), tool velocity in m/s in
                                    table coordinates, grip 0 or 1, yaw of the jaws in radians (optional)
  Robot      hand_pos()             where the tool is (m)         real: forward kinematics of the measured joints
             hand.grip, hand.held   commanded grip; what the pads hold   real: the twin's contacts, checked against the gripper
             grip_settled()         has the gripper stopped moving      real: from successive gripper readings
             go_rest()              park the arm
             stop() / resume()      emergency stop (torque off on a real arm)
  Scene      obj_pos(name), tilt(name)   where an object is, how far it leans   real: the twin's belief; a camera later (PR12)
             things(), half(), radius(), tallest(), layout        sizes and places from the scan (the twin)
  Geometry   reachable(xy), can_grasp(name), refusal(name, goal), grasp_offset(name), grasp_yaw(name),
             carry_height(), workspace_sample(rng)               from the arm descriptor and the twin's IK
  Planning   twin                   the World used to imagine (for the sim back-end: itself); clone() copies its state

`d` and `hs` arguments (MjData and HandState) select a copy made by `clone()`: they always refer to the twin.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

import numpy as np

CONTRACT = ("step", "hand_pos", "grip_settled", "go_rest", "stop", "resume", "close", "obj_pos", "tilt", "things", "half",
            "radius", "tallest", "reachable", "can_grasp", "refusal", "grasp_offset", "grasp_yaw", "carry_height",
            "workspace_sample", "clone", "settle", "arm_ready")


@runtime_checkable
class Backend(Protocol):
    name: str
    hand: object          # .grip (commanded), .held (name of the object the pads hold, or None), .target, .yaw
    layout: object
    twin: object

    def step(self, action, d=None, hs=None) -> None: ...
    def hand_pos(self, d=None) -> np.ndarray: ...
    def grip_settled(self, d=None) -> bool: ...
    def go_rest(self, d=None, hs=None, teleport: bool = False) -> None: ...
    def stop(self) -> None: ...
    def resume(self) -> None: ...
    def close(self) -> None: ...
    def arm_ready(self) -> bool: ...
    def obj_pos(self, name: str, d=None) -> np.ndarray: ...
    def tilt(self, name: str, d=None) -> float: ...
    def things(self) -> list: ...
    def half(self, name: str) -> float: ...
    def radius(self, name: str) -> float: ...
    def tallest(self) -> float: ...
    def reachable(self, xy, z: float = 0.02) -> bool: ...
    def can_grasp(self, name: str) -> tuple: ...
    def refusal(self, name: str, goal_xy=None) -> str: ...
    def grasp_offset(self, name: str) -> np.ndarray: ...
    def grasp_yaw(self, name: str) -> float: ...
    def carry_height(self) -> float: ...
    def workspace_sample(self, rng) -> tuple: ...
    def clone(self) -> tuple: ...
    def settle(self, ticks: int = 20) -> None: ...


def missing(obj) -> list[str]:
    """The names of the contract that `obj` does not provide (empty when it is a complete back-end)."""
    return [n for n in CONTRACT if not callable(getattr(obj, n, None))]
